gems:

repositories:
  remote:
    - http://repo1.maven.org/maven2
    - https://oss.sonatype.org/content/repositories/snapshots/

artifacts:
  molecule: com.vtence.molecule:molecule:jar:0.4-SNAPSHOT
  simple: org.simpleframework:simple:jar:5.1.6
  gson: com.google.code.gson:gson:jar:2.2.4
  mustache: com.samskivert:jmustache:jar:1.9

  # -- test dependencies
  jmock: org.jmock:jmock:jar:2.6.0
  hamcrest: org.hamcrest:hamcrest-all:jar:1.3
  molecule_tests: com.vtence.molecule:molecule:jar:tests:0.4-SNAPSHOT
  juniversalchardet: com.googlecode.juniversalchardet:juniversalchardet:jar:1.0.3
  htmlunit: net.sourceforge.htmlunit:htmlunit:jar:2.14

junit: 4.11
jmock: 2.6.0