gems:

repositories:
  remote:
    - http://repo1.maven.org/maven2

artifacts:
  molecule: com.vtence.molecule:molecule:jar:0.1
  simple: org.simpleframework:simple:jar:4.1.21

  # -- test dependencies
  jmock: org.jmock:jmock:jar:2.6.0
  hamcrest: org.hamcrest:hamcrest-all:jar:1.3

junit: 4.11
jmock: 2.6.0